#! /usr/bin/env bash
kernel="/home/jingde/linux-source-4.18.0/arch/x86/boot/bzImage"
image="/home/jingde/work/qemu-img.qcow2"
image="/home/jingde/work/qemu-image.img"
sudo qemu-system-x86_64 -kernel $kernel -nographic -hda $image -append "root=/dev/sda rw console=ttyS0" -k en-us --enable-kvm -smp cpus=4 -cpu host -m 512 -netdev user,id=user.0 -device e1000,netdev=user.0
