#! /usr/bin/env bash
kernel="/boot/vmlinuz-$(uname -r)"
kernel="vmroot/usr/src/linux-4.15/arch/x86/boot/bzImage"
kernel="linux-4.15/arch/x86/boot/bzImage"
image="vm.img"
sudo qemu-system-x86_64 \
    -kernel $kernel \
    -nographic \
    -hda $image \
    -append "root=/dev/sda rw console=ttyS0" -k en-us \
    -numa node,nodeid=0 -numa node,nodeid=1 \
    -smp cpus=4 -m 512 \
    -net nic, -net user
    # -netdev user,id=user.0 -device e1000,netdev=user.0
